name: test-automation-pipeline
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  hello-testbash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: echo `Hello TestBash`

